### ISSUE TITLE
Implement unic-ucd-ident

### ISSUE THREAD

**Issue by behnam** [behnam/rust-unic#133]
Char Properties:
* `ID_Start`/`ID_Continue`
* `XID_Start`/`XID_Continue`
* `Pattern_Syntax`/`Pattern_White_Space`

References:
* http://www.unicode.org/reports/tr44/tr44-4.html#ID_Start
* http://www.unicode.org/reports/tr31/

Cross-component tests:
* http://www.unicode.org/reports/tr31/#Table_Lexical_Classes_for_Identifiers

Similar crates:
* https://github.com/unicode-rs/unicode-xid

**Comment by CAD97** [comment]
The main use-case I have for this crate has a want for the `XID_*` and `Pattern_*` properties. I therefor can knock this component out, but I'd like to land #136 first.

**Comment by CAD97** [comment]
Request for a second opinion.

https://github.com/CAD97/rust-unic/commit/6969236a703bce87602c0286e614f1ec0f1997ef

This lightens the `*_continue` tables by a little under 1.5KB (1474 `char`) if my math is correct. However, it also means that checking a character's membership in `xid_continue` or `id_continue` will take about eight more comparisons (to a range) (over two tables instead of one). This does seem like a small difference once I did the math (`log2(line_count(new_continue)) - log2(line_count(old_continue)) + log2(line_count(start))`, but I want your opinion on whether the size optimization is worth it.

**Comment by CAD97** [comment]
On the above:

I realized that this would mean that the `*_continue` properties could not use the macro constructor if I do that, as the `is_*_continue` fn would have to be modified to check both tables. I guess that's a path for future possible benchmark+optimization, but for now I'm going to not use that optimization.
