### ISSUE TITLE
Is unic-ucd-indent available somewhere?

### ISSUE THREAD

**Issue by matklad** [behnam/rust-unic#192]
Hi! I'd love to use unic-ucd-indent crate (https://github.com/behnam/rust-unic/tree/master/unic/ucd/ident) for `is_pattern_whitespace property, but I am not able to find it on crates.io. Is it available somewhere?

**Comment by behnam** [comment]
Hey Aleksey,

The unic-ucd-ident componente is added in the latest version and is not
published yet. I'm making a release right after the holidays, which would
address that.

In the meanwhile, you can use the github repo in your Cargol.toml.

B


On Dec 29, 2017 3:30 PM, "Aleksey Kladov" <notifications@github.com> wrote:

Hi! I'd love to use unic-ucd-indent crate (https://github.com/behnam/
rust-unic/tree/master/unic/ucd/ident) for `is_pattern_whitespace property,
but I am not able to find it on crates.io. Is it available somewhere?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/behnam/rust-unic/issues/192>, or mute the thread

**Comment by matklad** [comment]
Great, thanks for the clarification! Looking forward to the new release! :)
