### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by CAD97** [behnam/rust-unic#194]
[We've had a good deal of changes made since the last release.](https://github.com/behnam/rust-unic/compare/v0.6.0...masterr)

Could we get version 0.7.0 released?

----

- Bumped minimum Rust to 1.22
- A lot of internal structure updates
- Added
  - unic/emoji/char
  - unic/segment
  - unic/ucd/common
  - unic/ucd/ident
  - unic/ucd/segment

**Comment by behnam** [comment]
Yeah, it's been in my shortlist for this weekend! I'll get to it in the evening! :)

**Comment by behnam** [comment]
Uh... have to push it back a couple of days, again. Sorry for the delays. It's on top of the list now and will be done in a day or two!

**Comment by behnam** [comment]
Okay, I'm done with the fixes needed for the release. Waiting for tests to pass and will cut the release in the morning.

----

Version: v0.7.0

# New Unicode character property components
- [`unic-ucd-common `] common character properties (*alphabetic*, *alphanumeric*, *control*, *numeric*, and *white_space*).
- [`unic-ucd-ident`] Unicode Identifier character properties.
- [`unic-ucd-segment`] Unicode Segmentation character properties.
- [`unic-emoji-char`] Unicode Emoji character properties.

# New Unicode algorithm components
- [`unic-segment`] Implementation of Unicode Text Segmentation algorithms (*Grapheme Cluster* and *Word* boundaries).

# Other updates
- Bumped minimum Rust to `1.22.0`, because of workspace build issues with earlier versions.
- Lots of small fixes for data types and internal structure updates.

**Comment by behnam** [comment]
Okay, there are a couple of more fixes I want to get in before release. Hopefully this evening.

**Comment by behnam** [comment]
Done: https://github.com/behnam/rust-unic/releases/tag/v0.7.0

More: https://users.rust-lang.org/t/unic-0-7-0-and-unic-cli-app/15481
